import argparse
import base64
import os
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from mc_common import (
    read_json,
    detect_arch,
    ensure_java_runtime,
    find_java,
    format_cmd,
    default_minecraft_dir,
)


def ensure_eula(server_dir):
    eula_path = server_dir / "eula.txt"
    eula_content = "# Generated by mini launcher\n" "eula=true\n"
    eula_path.write_text(eula_content, encoding="utf-8")


def set_online_mode(server_dir, online):
    props_path = server_dir / "server.properties"
    value = "true" if online else "false"
    if props_path.exists():
        lines = props_path.read_text(encoding="utf-8").splitlines()
        new_lines = []
        found = False
        for line in lines:
            if line.startswith("online-mode="):
                new_lines.append(f"online-mode={value}")
                found = True
            else:
                new_lines.append(line)
        if not found:
            new_lines.append(f"online-mode={value}")
        props_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    else:
        props_path.write_text(f"online-mode={value}\n", encoding="utf-8")


def _encode_ps_command(script):
    return base64.b64encode(script.encode("utf-16-le")).decode("ascii")


def find_running_server_pids(server_jar):
    target = str(server_jar.resolve())
    if sys.platform == "win32":
        script = (
            "$target = $env:_MC_SERVER_JAR_PATH; "
            "Get-CimInstance Win32_Process "
            "| Where-Object { $_.Name -in @('java.exe','javaw.exe') -and $_.CommandLine -like ('*' + $target + '*') } "
            "| Select-Object -ExpandProperty ProcessId"
        )
        encoded = _encode_ps_command(script)
        env = os.environ.copy()
        env["_MC_SERVER_JAR_PATH"] = target
        proc = subprocess.run(
            ["powershell", "-NoProfile", "-EncodedCommand", encoded],
            capture_output=True,
            text=True,
            env=env,
        )
    else:
        proc = subprocess.run(
            ["pgrep", "-f", target],
            capture_output=True,
            text=True,
        )
    if proc.returncode != 0:
        return []
    pids = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            pids.append(int(line))
        except ValueError:
            continue
    return sorted(set(pids))


def kill_pid_tree(pid):
    if sys.platform == "win32":
        proc = subprocess.run(
            ["taskkill", "/PID", str(pid), "/T", "/F"],
            capture_output=True,
            text=True,
        )
    else:
        proc = subprocess.run(
            ["kill", "-TERM", str(pid)],
            capture_output=True,
            text=True,
        )
    return proc.returncode == 0


def main():
    default_minecraft = default_minecraft_dir()
    parser = argparse.ArgumentParser(
        description="Launch Minecraft dedicated server."
    )
    parser.add_argument("version_id", help="Version id, e.g. 1.21.11")
    parser.add_argument(
        "--servers-dir",
        default=".minecraft/servers",
        help="Root folder for server instances",
    )
    parser.add_argument(
        "--minecraft-dir",
        default=str(default_minecraft),
        help="Path to .minecraft for runtime lookup/download",
    )
    parser.add_argument("--java", default=None, help="Path to java.exe")
    parser.add_argument("--xmx", default="2G", help="Max memory, e.g. 4G")
    parser.add_argument("--xms", default=None, help="Min memory, e.g. 1G")
    parser.add_argument(
        "--gui",
        action="store_true",
        help="Run server with GUI (default is nogui)",
    )
    parser.add_argument(
        "--accept-eula",
        action="store_true",
        help="Write eula.txt with eula=true before launch",
    )
    parser.add_argument(
        "--restart-if-running",
        action="store_true",
        help="If server process for this folder is running, kill it and relaunch",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print command and exit")
    parser.add_argument(
        "--offline-mode",
        action="store_true",
        help="Set online-mode=false in server.properties (allows offline/cracked clients)",
    )
    args = parser.parse_args()

    servers_dir = Path(args.servers_dir)
    minecraft_dir = Path(args.minecraft_dir)
    server_dir = servers_dir / args.version_id
    server_jar = server_dir / "server.jar"
    version_json = server_dir / f"{args.version_id}.json"

    if not server_jar.exists():
        print(f"missing server jar: {server_jar}", file=sys.stderr)
        print("run download_server_windows.py first", file=sys.stderr)
        return 1

    java_exe = args.java
    if not java_exe and version_json.exists():
        version_data = read_json(version_json)
        component = version_data.get("javaVersion", {}).get("component")
        if component:
            java_exe = ensure_java_runtime(minecraft_dir, component, detect_arch()[0])
    if not java_exe:
        java_exe = find_java(None)
    if not java_exe:
        print("java not found; use --java to set explicit path", file=sys.stderr)
        return 1

    cmd = [str(java_exe)]
    if args.xms:
        cmd.append(f"-Xms{args.xms}")
    if args.xmx:
        cmd.append(f"-Xmx{args.xmx}")
    cmd += ["-jar", str(server_jar)]
    if not args.gui:
        cmd.append("nogui")

    print(f"version: {args.version_id}")
    print(f"server_dir: {server_dir}")
    print(f"minecraft_dir: {minecraft_dir}")
    if args.dry_run:
        running_pids = find_running_server_pids(server_jar)
        if running_pids:
            print(f"note: running server process(es): {', '.join(str(p) for p in running_pids)}")
            if args.restart_if_running:
                print("note: --restart-if-running would stop those processes before launch")
        print("dry run: command follows")
        print(format_cmd(cmd))
        return 0

    if args.accept_eula:
        ensure_eula(server_dir)
    if args.offline_mode:
        set_online_mode(server_dir, online=False)

    running_pids = find_running_server_pids(server_jar)
    if running_pids:
        if args.restart_if_running:
            print(f"found running server process(es): {', '.join(str(p) for p in running_pids)}")
            for pid in running_pids:
                if kill_pid_tree(pid):
                    print(f"stopped pid {pid}")
                else:
                    print(f"warning: could not stop pid {pid}")
            time.sleep(1.5)
        else:
            print(
                "server already running for this folder; skipping launch "
                "(use --restart-if-running to relaunch)"
            )
            return 0

    return subprocess.call(cmd, cwd=server_dir)


if __name__ == "__main__":
    raise SystemExit(main())
